fixed bug
the-collab-lab/tcl-44-smart-shopping-list pull request #32
Opened 2022-05-18 15:51 UTC by OloyedeTobi

## Description

This PR fixes the bug with the delete button as pointed out by @hellodeborahuk 
- I added the `e.stopPropagation `method to the `deleteItems` function to prevent event propagation from child to parent component or vice versa.
- I wrapped the delete icon in a `button` tag to improve accessibility.

## Related Issue

closes #27 

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|  ✓| :bug: Bug fix              |
|    | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

## Testing Steps / QA Criteria

- From your terminal, pull down this branch with git pull origin `to-fix-delete-bug` and check that branch out with git checkout `to-fix-delete-bug`.
- Then npm start to launch the app.
- Click on the delete icon in front of any item to attempt deleting it.
- Observe if an unchecked checkbox is checked after clicking on the delete icon. 
CLICKING ON THE DELETE BUTTON SHOULD NOT CHECK OUT AN UNCHECKED CHECKBOX

2022-05-18 22:03 UTC, redapy requested changes
Great job Tobi! I suggested some other changes

2022-05-18 22:03 UTC, redapy commented on src/components/ListItem.js
> +      </button>
Can you move the onClick to the button? it's a bad practice to add `eventListener` to an icon.

2022-05-18 22:03 UTC, redapy commented on src/components/ListItem.js
> +     e.stopPropagation()
The bug was caused by the icon being inside a span. Now when we are using a button instead the bug does not exist anymore. so you can delete this `e.stopPropagation()`.

2022-05-19 06:29 UTC, JimeBlue commented on src/components/ListItem.js
> +     e.stopPropagation()
Great job @OloyedeTobi! I agree with Reda´s comments and have nothing further to add.

2022-05-19 06:42 UTC, hellodeborahuk commented on src/components/ListItem.js
> +     e.stopPropagation()
Great job Tobi! Ditto what Reda and Jimena have said.

2022-05-19 11:45 UTC, OloyedeTobi commented on src/components/ListItem.js
> +      </button>
oh! Thanks for that. I'll fix that

2022-05-19 13:10 UTC, redapy approved these changes
LGTM!

2022-05-19 13:38 UTC, merged